const questions = [
    { question: "The reciprocal of a fraction cannot be ___", answer: "0" },
    { question: "What is the name of the theorem that relates sine and cosine?", answer: "pythagoras theorem" },
    { question: "A rectangle has a perimeter of 110 units. If the length is 30 units, what is the width?", answer: "25" },
    { question: "What is the conjugate of x+iy?", answer: "x-iy" },
    { question: "A 10-meter ladder is leaning against a wall, with the base 6 meters away from the wall. How far up the wall does the ladder reach? (do not enter units)", answer: "8" },
    { question: "The sum of three consecutive integers in 33. Enter the largest integer.", answer: "12" },
    { question: "What's the next number in this sequence? 2,3,5,9,17,_ ", answer: "33" },
    { question: "A farmer has 17 sheep, and all but 9 die. How many are left?", answer: "9" },
    { question: "How many times can you subtract 5 from 25", answer: "1" },
    { question: "What is 75% of 75?", answer: "56.25" },
    { question: "If a train leaves the station traveling at 50 mph, how far will it go in 2 hours? (do not mention units)", answer: "100" },
    { question: "If you flip a fair coin three times, what is the probability of getting exactly two heads?", answer: "3/8" },
    { question: "If it takes 3 machines 3 minutes to make 3 widgets, how long would it take 100 machines to make 100 widgets?", answer: "3" },
    { question: "If 4ˣ+4ˣ⁺¹=320, find x.", answer: "3" },
    { question: "A number is multiplied by 4 and then decreased by 16, resulting in 48. What is the number?", answer: "16" },
    { question:" A man is twice as old as his son. In 20 years, he will be 1.5 times as old as his son. How old is the father?", answer: "40" },
    { question: "In a triangle, the three angles are in the ratio 2:3:4. What is the largest angle?", answer: "80" },
    { question: "How many days are there in x weeks x days?", answer: "8x" },
    { question: "In a garden, the ratio of the number of coconut trees to that of mango trees is 5:6 respectively. If the total number of trees is 121, then how many coconut trees are there in the garden??", answer: "55" },
    { question: "What is the probability of rolling two dice and getting a sum of 8?", answer: "5/36" },
    { question: "The branch of mathematics that deals with the study of shapes, sizes, properties of space, and the relationships between different figures", answer: "geometry" },
    { question: "The sides of a triangle are 7cm, 24cm and 25cm, what is the area of the triangle?", answer: "84" },
    { question: "A classroom has 48 pencils. If each student gets 3 pencils and there are 12 students. If the teacher then buys 20 more pencils, how many pencils are left in the classroom now??", answer: "32" },
    { question: "If P means '+', Q means '-', R means '×' and S means '÷', then the value of the following expression?\n40 S 4 R 2 P 19 Q 26", answer: "13" },
    { question: "Find the number of diagonals in a hexagon.", answer: "9" },
    { question: "A clock gains 5 minutes every hour. How many minutes fast will it be after 24 hours?", answer: "120" },
    { question: "What is the sum of the squares of the first 10 natural numbers?", answer: "385" },
    { question: "What is the product of of distinct prime factors of 360?", answer: "30" },
    { question: "A and B can do a work together in 18 days. A is three times as efficient as B. In how many days B alone can complete the work?", answer: "72" },
    { question: "If 1=3\n2=3\n3=5\n4=4\n5=4\nThen, 6=", answer: "3" },
    { question: "A sum of money becomes 7/4 of itself in 6 years at simple interest. What is the rate of interest?", answer: "12.5" },
    { question: "What number 9 times equals 2340?", answer: "260" },
    { question: "If 2p+3q=18 and 2p-q=2, then 2p+q=?", answer: "10" },
    { question: "The study of likelihood and uncertainty, focusing on how likely it is that an event will occur?", answer: "probability" },
    { question: "Which is the greatest number which will divide  1600 and 1420 exactly?", answer: "20" },
    { question: "Two times of a number, added to the square of that number, gives 3. Give the product of the possible values of that number.", answer: "-3" },
    { question: "A mathematical statement that has been proven to be true based on previously established statements, such as axioms and postulates?", answer: "theorem" },
    { question: "In a class of 30 students, 18 students passed the math exam. If 6 more students pass in the next exam, what will be the difference in the pass percentage?", answer: "20%" },
    { question: "What is the sum of all angles of a polygon with 8 sides?", answer: "1080" },
    { question: "A shopkeeper bought a watch for Rs.1200. At what price should he sell thaT watch to earn a profit of 25%?", answer: "1500" },
    { question: "A man can row 5 km/h in still water. If the river is flowing at 2 km/h, and he rows upstream for 2 hours, how far will he have traveled? (in km)", answer: "6" },
    { question: "A sum of money is to be distributed among A,B,C,D in the proportion of 5:2:4:3. If C gets Rs.1000 more than D, what is B's share?", answer: "2000" },
    { question: "A class has 30 students. If 18 students like mathematics, 15 students like science, and 10 students like both subjects, how many students like only mathematics?", answer: "8" },
    { question: "If 40% of a number is 180, what is the number?", answer: "450" },
    { question: "Given that simple interest on a certain sum of money is Rs. 4016.25 at 9% per annum in 5 years. Find the sum of money?", answer: "8925" },
    { question: "How many times do the hands of a clock coincide in a day?", answer: "22" },
    { question: "What is the probability of getting an even number when a dice is rolled?", answer: "1/2" },
    { question: "Find the odd man out: 10, 25, 45, 54, 60, 75, 80?", answer: "54" },
    { question: "A fruit seller had some apples. He sells 40% apples and still has 420 apples. Originally, he had:?", answer: "700" },];